config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :flats do
    collection do
      get 'my_flats', to: "flats#my_flats"
    end
    member do
      get 'my_flat', to: "flats#my_flat"
    end
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:index, :destroy, :update]
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :flat

  # after_create :send_email

  validates :nb_travelers, presence: true
  validates :flat, presence: true
  validates :user, presence:true
  validates :start_date, presence:true
  validates :end_date, presence:true

  # def send_email
  #   UserMailer.booking(self).deliver_now
  # end
end

app/models/flat.rb
class Flat < ActiveRecord::Base
  belongs_to :user
  has_many :bookings
  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :title, presence: true
  validates :address, presence: true
  validates :capacity, presence: true
  validates :price_per_night, presence: true
  validates :city, presence: true
  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :flats
  has_many :bookings
  has_attached_file :picture,

    styles: { medium: "300x300>", thumb: ["50x50#", :png] }


  # after_create :send_welcome_email

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.name = auth.info.name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

  private

  # def send_welcome_email
  #   UserMailer.welcome(self).deliver_now
  # end
end

app/models/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit( :email, :password, :password_confirmation, :first_name, :last_name, :description, :picture) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :first_name, :last_name, :name, :description, :picture) }
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
before_action :set_booking, only: [ :destroy, :update ]

  def index
    @bookings = current_user.bookings
    @my_flats = current_user.flats
    @bookings_client = []
    @my_flats.each do |flat|
      @bookings_client << flat.bookings
    end
    @bookings_client.flatten!
  end

  def new
    @booking = Booking.new
    @flat = Flat.find(params[:flat_id])
  end

  def create
    @flat = Flat.find(params[:flat_id])
    @booking = @flat.bookings.new(booking_params)
    @booking.user = current_user
    @booking.status = "pending"
    if @booking.save
      redirect_to bookings_path(current_user)
    else
      render 'flats/show'
    end
  end

  def update
    if params[:accept] == "true"
      # Accepter le booking dans la bdd donc changer le statut
      @booking.update(status: 'confirmed')
    else
      @booking.update(status: 'refused')
    end
    redirect_to :back
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end



  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:nb_travelers, :start_date, :end_date, :message)
  end

end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: [ :show, :edit, :update, :destroy, :my_flat ]
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    if params[:city] && params[:capacity]
      @flats = Flat.where(city: params[:city])
        .where("capacity >= ?", params[:capacity])
    else
      @flats = Flat.all
    end
    # Let's DYNAMICALLY build the markers for the view.
    @markers = Gmaps4rails.build_markers(@flats) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
    end
  end

  def show
    @booking = Booking.new
    @flats = []
    @flats << @flat
    # Let's DYNAMICALLY build the markers for the view.
    @markers = Gmaps4rails.build_markers(@flats) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
    end
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = current_user.flats.build(flat_params)
    if @flat.save
      redirect_to my_flats_flats_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to my_flats_flats_path
  end

  def destroy
    @flat.destroy
    redirect_to my_flats_flats_path
  end

  def my_flats
    @my_flats = current_user.flats
    # Let's DYNAMICALLY build the markers for the view.
    @markers = Gmaps4rails.build_markers(@my_flats) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
    end
  end

  def my_flat
    @flats = []
    @flats << @flat
    # Let's DYNAMICALLY build the markers for the view.
    @markers = Gmaps4rails.build_markers(@flats) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
    end
  end

  private

  def find_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:user_id, :title, :address, :city, :description, :price_per_night, :capacity, :picture)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @cities = Flat.select(:city).distinct.map { |flat| flat.city }
    @capacities = Flat.select(:capacity).distinct.map{ |flat| flat.capacity }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookings/index.html.erb
    <div class="container ">
      <div class= "white_card ">
      <h1>All my bookings </h1>

        <% if @bookings.first == nil %>
          <p> You currently have no bookings! Come & rent <%= link_to "here", root_path %> !</p>
        <% else %>
          <table class="bookings table table-striped">
            <tbody>
              <% @bookings.each do |booking| %>
                <tr class="shadow-table">
                  <td ><%= link_to booking.flat.title, flat_path(booking.flat)%></td>
                  <td ><%= booking.start_date%> au <%= booking.end_date %></td>
                  <td><%= booking.nb_travelers%></td>
                  <td><%= booking.status %></td>
                  <td>
                    <%= link_to booking_path(booking),
                        method: :delete,
                        data: { confirm: "Are you sure?" } do %>
                        <i class="fa fa-trash-o"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
     </div>
  </div>
  <br>
    <div class="container">
     <div class= "white_card">
      <h1>All the bookings on my flats  </h1>
        <table class="bookings table">
          <% @bookings_client.each do |booking| %>
            <tbody>
              <tr class="shadow-table">
                <td ><%= link_to booking.flat.title, flat_path(booking.flat)%></td>
                <td ><%= booking.start_date%> au <%= booking.end_date %></td>
                <td><%= booking.nb_travelers%></td>
                <td><%= booking.status %></td>

                <td>
                  <ul class="list-inline">
                    <li>
                      <%= button_to("Accept", { action: "update", id: booking.id }, { method: :put, params: { accept: true }, class: "btn btn-success" } ) %>
                    </li>
                    <li>
                      <%= button_to "Refuse", { action: "update", id: booking.id }, method: :put, params: { accept: false }, class: "btn btn-success" %>
                    </li>
                  </ul>
                </td>




              <% end %>
            </tr>
          </tbody>
        </table>
    </div>
  </div>

app/views/flats/_flat_form.html.erb
<div class= "white_card">
  <%= simple_form_for [@user, @flat], html: { multipart: true } do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :price_per_night %>
    <%= f.input :capacity %>
    <%= f.input :picture %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/flats/delete.html.erb
<h1>Flats#delete</h1>
<p>Find me in app/views/flats/delete.html.erb</p>

app/views/flats/edit.html.erb
<h1>Edit Your Flat "<%= @flat.title %>"</h1>
<br>

<%= render 'flat_form' %>

app/views/flats/index.html.erb
<div class="container">
  <div class= "white_card">
    <div class= "row padded">
      <h1><%= @flats.size %> Search results</h1>

      <br>
        <div id="map" style='width: 750px; height: 200px'></div>
        <% content_for(:after_js) do %>
          <script type="text/javascript">
            $(document).on('ready', function() {
              handler = Gmaps.build('Google');
              handler.buildMap({ internal: { id: 'map' } }, function(){
                markers = handler.addMarkers(<%= raw @markers.to_json %>);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
                handler.getMap().setZoom(12);
              });
            })
          </script>
        <% end %>

      <% @flats.each do |flat| %>
        <div class= "col-md-6">
          <div class= "card-place">
            <div class="card-place-header"
                style="background-image: url(<%= flat.picture.url(:medium)%>);">
            </div>
            <div class="card-place-body relative">
              <h3><%= link_to flat.title, flat_path(flat) %></h3>
              <p><%= flat.price_per_night %>€/night</p>
              <p><%= flat.capacity %> persons</span></p>
              <p><%= flat.description %></p>
              <div class= "position">
              <%= image_tag flat.user.picture.url(:medium), class: "img-circle size"%>
              </div>
            </div>

            <div class="card-place-footer">
              <%= link_to flat_path(flat) do %>
                <i class="fa fa-search"></i>
              <% end %>
            </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

<br>
<div class="text-center"><%= link_to "Rent Your Flat", new_flat_path, class: "btn btn-success" %></div>

app/views/flats/my_flat.html.erb
<br>
<div class="container"></div>
  <div class="row">
    <div class="col-xs-12 col-md-6">

      <div class="white_card">
        <h1><%= @flat.title %></h1>
        <p><%= @flat.city %></p>
        <br>
        <%= image_tag @flat.picture.url(:medium) %>
        <br>
        <br>
        <p><%= @flat.price_per_night %>€ / night - <%= @flat.capacity %> persons</p>
        <p><%= @flat.address %></p>
      </div>

    </div>
    <div class="col-xs-12 col-md-6">

      <div id="map" style='width: 400px; height: 400px'></div>
      <% content_for(:after_js) do %>
        <script type="text/javascript">
          $(document).on('ready', function() {
            handler = Gmaps.build('Google');
            handler.buildMap({ internal: { id: 'map' } }, function(){
              markers = handler.addMarkers(<%= raw @markers.to_json %>);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
              handler.getMap().setZoom(12);
            });
          })
        </script>
      <% end %>

    </div>
  </div>
</div>

<br>
<div class="text-center"><%= link_to "Back to My Flats", my_flats_flats_path %></div>

app/views/flats/my_flats.html.erb
<div class="container">
    <div class= "white_card">
      <h1>My Profile</h1>

      <p><%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-success" %></p>
  <br>

      <p>Email: <%= current_user.email %></p>
      <p>First name: <%= current_user.first_name %></p>
      <p>Last name: <%= current_user.last_name %></p>

      <%= image_tag current_user.picture.url(:medium) %>
  <br>
      <p>Email: <%= current_user.email %></p>
      <p>Profile created at: <%= current_user.created_at %></p>

      <br>
      <p><%= link_to "Go to My Bookings", bookings_path %></p>

  <br>
  <br>
    </div>
</div>

<div class="container">
  <div class= "white_card">
    <div class= "row padded">
      <h1>My Flats</h1>
      <% @my_flats.each do |flat| %>
        <div class= "col-md-6">
          <div class= "card-place">
            <div class="card-place-header"
                  style="background-image: url(<%= flat.picture.url(:medium)%>);">
            </div>
            <div class="card-place-body">
              <h3><%= link_to flat.title, flat_path(flat) %></h3>
              <p><%= flat.city %></p>
              <p><%= flat.description %> </p>
              <p><%= flat.price_per_night %>€ / night, <%= flat.capacity %> persons</p>
            </div>
            <div class="card-place-footer">
              <%= link_to edit_flat_path(flat) do %>
                <i class="fa fa-pencil"></i>
              <% end %>
              <%= link_to flat_path(flat),
                method: :delete,
                data: { confirm: "Are you sure?" } do %>
                <i class="fa fa-trash"></i>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
      <br>
    </div>
    <p><%= link_to "Add a new flat", new_flat_path, class: "btn btn-success" %></p>
  </div>
</div>

app/views/flats/new.html.erb
<h1 class="text-center" >Rent Your Flat</h1>

<%= render 'flat_form' %>

app/views/flats/show.html.erb
 <div class="white_card">
<div class="container"></div>
  <div class="row">

      <div class="col-md-6">
        <h1><%= @flat.title %></h1>
        <p><%= @flat.city %></p>
        <br>
        <%= image_tag @flat.picture.url(:medium) %>
        <br>
        <br>
        <p><%= @flat.price_per_night %>€ / night - <%= @flat.capacity %> persons</p>
        <p><%= @flat.address %></p>

      </div>

    <div class="col-md-6">
      <div id="map" style='width: 500px; height: 400px'></div>
      <% content_for(:after_js) do %>
        <script type="text/javascript">
          $(document).on('ready', function() {
            handler = Gmaps.build('Google');
            handler.buildMap({ internal: { id: 'map' } }, function(){
              markers = handler.addMarkers(<%= raw @markers.to_json %>);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
              handler.getMap().setZoom(12);
            });
          })
        </script>
      <% end %>
    </div>


      <h2>Book</h2>
      <%= simple_form_for [@flat, @booking] do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :nb_travelers %>
          <%= f.input :start_date %>
          <%= f.input :end_date %>
          <%= f.input :message %>
        </div>
        <div class="form-actions text-center">
          <%= f.submit "Book", class: "btn btn-success btn-lg" %>
        </div>
      <% end %>

  </div>
</div>

<br>
<div class="text-center"><%= link_to "Back to Search results", my_flats_flats_path %></div>


</div>
</div>

app/views/flats/update.html.erb
<h1>Flats#update</h1>
<p>Find me in app/views/flats/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Tamadi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= javascript_include_tag "https://maps.google.com/maps/api/js?sensor=false" %>
  <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>

  <%= javascript_include_tag "application" %>

</head>

<body>

  <%= render "shared/notices" %>

  <%= render "shared/navbar" %>

  <%= yield %>

  <%= yield(:after_js) %>
  <%= render "shared/footer" %>
</body>
</html>

app/views/pages/home.html.erb
<div class="banner window-height">
  <div class="container">
     <h1>Meet Real France</h1>
     <br>
     <br>
     <p>
        Live the life of true French people !
     </p>
  <div class= "searchbar">
    <div class= "container">
      <div class= "row">
        <%= form_tag(flats_path, method: :get, class: "form-inline") do %>
          <%= select_tag "city", options_for_select(@cities), prompt: "Select city", class: "form-control" %>
          <%= number_field_tag "capacity", nil, placeholder: 'num of travellers', class: "form-control" %>
          <%= submit_tag "Meet your French home", class: "btn btn-success" %>
         <br>
         <br>
         <br>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>
  <div class="features">
    <div class="container text-center" >
      <div class="row">
        <div class="col-sm-4 padding-sides-15">
          <div class="card">
            <%= image_tag "livingroom1.jpg", class: "img-rounded img-size" %>
            <h2>Chez Jean-mi </h2>
            <p>Magnifique maison de 100 m2 dans le Vercors</p>
          </div>
        </div>

        <div class="col-sm-4 padding-sides-15">
          <div class="card" data-sr="wait 3s, ease-in-out 100px">
             <%= image_tag "livingroom4.jpg", class: "img-rounded img-size" %>
            <h2> Chez Bernadette </h2>
            <p> Il y'a toujours de la place pour des voyageurs dans la maison de Bernadette</p>
          </div>
        </div>

        <div class="col-sm-4 padding-sides-15">
          <div class="card" data-sr="wait 4s, ease-in-out 100px">
            <%= image_tag "livingroom2.jpg", class: "img-rounded img-size"%>
             <h2> Chez Jeannine</h2>
             <p>Tout est aménagé pour se sentir comme à la maison</p>
          </div>
        </div>

      </div>
    </div>


  </div>

  <div class="text-center padded" id ="news">
    <div class="container">
      <h2>Get news from RobertBnB</h2>
      <p>Leave us your mail</p>
      <form class="form-inline">
        <input type="email" placeholder="bob@gmail.com" class="form-control">
        <input type="submit" value="Subscribe" class="btn btn-primary">
      </form>
    </div>
  </div>



  <script>
      window.sr = new scrollReveal();
  </script>

app/views/shared/_footer.html.erb
 <div id="footer">
    <div class="container">
      <div class="row">
        <div class="col-xs-4">
          <ul class="list-inline">
            <li><a href=""><i class="fa fa-youtube"></i></a></li>
            <li><a href=""><i class="fa fa-instagram"></i></a></li>
            <li><a href=""><i class="fa fa-facebook"></i></a></li>
            <li><a href=""><i class="fa fa-twitter"></i></a></li>
          </ul>
        </div>
        <div class="col-xs-8 text-right">
          <p>Made with love by RobertBnB</p>
        </div>
      </div>
    </div>
  </div>
     <div class="modal fade" id="subscribe-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Sign Up ! </h4>
          </div>
          <div class="modal-body">
            <form action="">
              <div class="form-group">
                <label for="email" >Email</label>
                <input type="text" name="email" placeholder="tatianaperillo@yahoo.fr" class="form-control">
              </div>
              <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" placeholder="Tatiana Perillo" class="form-control">
              </div>
            </form>
          </div>
           <div class="modal-footer">
              <button type="button" class="btn btn-primary">Enter</button>
          </div>
        </div>
      </div>
  </div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-wagon" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag "logo.png" %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
          <!-- <li>
            <%= link_to "#" do %>
              <i class="fa fa-envelope-o"></i> <%= t(".messages", default: "Messages") %>
            <% end %>
          </li> -->
          <li class="dropdown">
            <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false"} do %>
              <% if current_user.picture? %>

                <%= image_tag current_user.picture.url(:thumb), class: "img-avatar" %>



              <% else %>
                <%= image_tag "http://placehold.it/30x30", class: "img-avatar" %>
              <% end %>
              Profile <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to my_flats_flats_path do %>
                  <i class="fa fa-user"></i> <%= t ".profile", default: "My Profile" %>
                <% end %>
              </li>
              <li>
                <%= link_to bookings_path do %>
                  <i class="fa fa-home"></i>  <%= t ".profile", default: "My Bookings" %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Sign out" %>
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path %>
          </li>
          <li>
            <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path %>
          </li>
        <% end %>
        <li>
          <%= link_to t(".top_call_to_action", default: "Rent your flat"), new_flat_path, class: "btn" %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_notices.html.erb
<% if notice %>

  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>

<% end %>
<% if alert %>

  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>

<% end %>